spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbphoneshopmgt
    username: phoneshop_mgt
    password: phoneshopmgt123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


